name: Build and Publish the Package
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      YARN_TOKEN: ${{ secrets.YARN_TOKEN }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: "16.x"
      - run: npm install -g yarn
      - run: yarn --no-default-rc
      - run: yarn build
      - run: npm publish
